---
- name: install redhat packages
  package:
    name: "{{ redhat_package_dependencies + _ceph_pkgs_to_install }}"
    state: present
  when:
    - ansible_distribution == 'RedHat'

- name: install centos packages
  package:
    name: "{{ centos_package_dependencies + _ceph_pkgs_to_install }}"
    state: present
  when:
    - ansible_distribution == 'CentOS'
