---
# ceph-common
- block:
  - name: create ceph conf directory
    file:
      path: "/etc/ceph"
      state: directory
      owner: "ceph"
      group: "ceph"
      mode: "0755"

  - name: "generate ceph configuration file: {{ cluster }}.conf"
    action: config_template
    args:
      src: ceph.conf.j2
      dest: /etc/ceph/{{ cluster }}.conf
      owner: "ceph"
      group: "ceph"
      mode: "0644"
      config_overrides: "{{ ceph_conf_overrides }}"
      config_type: ini
    notify:
      - restart ceph mons
      - restart ceph osds
      - restart ceph mdss
      - restart ceph rgws
      - restart ceph mgrs
      - restart ceph rbdmirrors
  when:
    - not containerized_deployment|bool

# ceph-docker-common
# only create fetch directory when:
# we are not populating kv_store with default ceph.conf AND host is a mon
# OR
# we are not population kv_store with default ceph.conf AND there at least 1 nfs in nfs group AND host is the first nfs
- block:
  - name: create a local fetch directory if it does not exist
    local_action:
      module: file
      path: "{{ fetch_directory }}"
      state: directory
    changed_when: false
    become: false
    run_once: true
    when:
      - (cephx or generate_fsid)
      - (not mon_containerized_default_ceph_conf_with_kv and
          (inventory_hostname in groups.get(mon_group_name, []))) or
        (not mon_containerized_default_ceph_conf_with_kv and
          ((groups.get(nfs_group_name, []) | length > 0)
            and (inventory_hostname == groups.get(nfs_group_name, [])[0])))

  - name: ensure /etc/ceph exists
    file:
      path: /etc/ceph
      state: directory
      owner: 'ceph'
      group: 'ceph'
      mode: 0755
    when:
      - groups.get(mon_group_name, []) | length == 0

  - name: "generate {{ cluster }}.conf configuration file"
    action: config_template
    args:
      src: "ceph.conf.j2"
      dest: "{{ ceph_conf_key_directory }}/{{ cluster }}.conf"
      owner: "root"
      group: "root"
      mode: "0644"
      config_overrides: "{{ ceph_conf_overrides }}"
      config_type: ini
    notify:
      - restart ceph mons
      - restart ceph osds
      - restart ceph mdss
      - restart ceph rgws
      - restart ceph mgrs
      - restart ceph rbdmirrors
